### ISSUE TITLE
多主多从高可用服务集群可实现吗

### ISSUE THREAD

**Issue by romanholidaypancakes** [ChenHuajun/blog_xqhx#1]
大佬你好，我看到这篇文章：[基于Patroni的Citus高可用环境部署](https://github.com/ChenHuajun/blog_xqhx/blob/main/2020/2020-09-07-%E5%9F%BA%E4%BA%8EPatroni%E7%9A%84Citus%E9%AB%98%E5%8F%AF%E7%94%A8%E7%8E%AF%E5%A2%83%E9%83%A8%E7%BD%B2.md)

看到里面是**一主多从**, 我担心 主服务写入压力过大，想使用**多主多从一键式方案**，不知是否可行，有相关文章推荐吗。谢谢

以下是我设计的一个草图

![test333](https://user-images.githubusercontent.com/51652878/134801481-2b9434dd-e1e9-4db5-b935-04940ad65111.png)

**Comment by romanholidaypancakes** [comment]
而且是属于多客户写的场景 ，读取反而较少

**Comment by ChenHuajun** [comment]
如果写压力过大，且垂直扩容仍解决不了，建议拆库或分库分表（含citus，tbase，antdb这种分布式方案）的方式分担负载。
